// game.js
// The primary game loop for the Sea Scavenger game.
//
// Code for Tucson
// 20 September 2020

// Game variables.
let splashScreenDisplayed = false;
let missionsCompleted = 0;
// Plastics collected is an object to keep a talley of the plastic waste 
// recovered in the missions. The properties are the field names from the 
// Combined Data Set contained in the CSV or JSON data file.
let plasticsCollected = {
    BucketOrCrate: 0,
    BuoysAndFloats: 0,
    CigaretteButts: 0,
    FishingGlowSticks: 0,
    FishingLineLureRope: 0,
    FishingNet: 0,
    LollipopStickOrEarBud: 0,
    Plastic_Beverage_Bottle: 0,
    Plastic_FoamFoodContainer: 0,
    PlasticBag: 0,
    PlasticBottleCapOrLid: 0,
    PlasticDrinkingStraw: 0,
    PlasticLighter: 0,
    PlasticOrFoamPlatesCupsSilverware: 0,
    PlasticPersonalCareProduct: 0,
    PlasticSheet: 0,
    PlasticStraps: 0,
    StringRingRibbon: 0,
    WrapperOrLabel: 0
};

// hideSplash
// Hide the splashscreen after giving player time to read it.
function hideSplash() {
    let splash = document.getElementById("splashscreen");
    splash.style.display = "none";
    splashScreenDisplayed = true;
    gameLoop();
}

// generateMission
// Generate a mission for the player to complete.
// The mission will consist of a plastic type to be collected, the number of
// pieces to be collected, a product to be made from the collected plastic, and
// six countries to collect the plastic from. Some of the countries will have a
// high likelihood of being able to achieve the mission and the others will have
// a low likelihood, as determined by parsing the plastics data.
// Returns a JS object containing the plastic type, number of 
// pieces, product, and countries.
const generateMission = function() {
    console.log("Generating mission.");
    let mission = {
        plasticType: "",
        numPieces: 0,
        product: "",
        countries: {
            country1: "",
            country2: "",
            country3: "",
            country4: "",
            country5: "",
            country6: ""
        }

    };
    return mission;
}

// acceptMission
// Display the mission generated by the generateMission function and prompt
// the user to accept it.
// Return true if user accepts and false otherwise.
const acceptMission = function(mission) {
    console.log("Accept mission?");
    let missionScreen = document.getElementById("missionscreen");
    missionScreen.style.display = "block";
    return true;
}

// executeMission
// Interact with the player to assign and execute a mission. 
// If the mission is successful, return true, else false. 
const executeMission = function() {
    console.log("Executing mission...");
    let mission = generateMission();
    if (acceptMission(mission)) {
        missionsCompleted++;
        console.log("Mission #%d:", missionsCompleted);
        console.log(mission);
    }

    return false;
}

// gameLoop
// The main loop to control game execution.
function gameLoop() {
    console.log("The game loop is running!");
    let play = true;
    while (play) {
        play = executeMission();
    }
}

// Event listener that executes when the page has loaded to start the game loop.
// The loop will run until a mission is not successful.
window.addEventListener("load" , event => {
    if (!splashScreenDisplayed) {
        window.setTimeout(hideSplash, 30000);
    } else {
        gameLoop();
    }
});